# Generated by Django 6.0.6 on 2026-07-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oauthcredential_onboardingprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='business_usp',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='target_audience',
        ),
    ]
