# Generated by Django 6.0.6 on 2026-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_onboardingprofile_business_usp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcredential',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
