# Generated by Django 6.0.6 on 2026-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_oauthcredential_google_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprofile',
            name='selected_campaigns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
