# Generated by Django 6.0.6 on 2026-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_onboardingprofile_selected_campaigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='selected_campaigns',
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='selected_campaigns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
