# Generated by Django 6.0.6 on 2026-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_onboardingprofile_selected_campaigns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcredential',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
