# Generated by Django 6.0.6 on 2026-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_onboardingprofile_bigquery_dataset_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprofile',
            name='mcc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
